# Generated by Django 5.2.14 on 2026-05-27 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва матеріалу')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за грам')),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва моделі')),
                ('description', models.TextField(verbose_name='Опис')),
                ('recommended_size', models.CharField(max_length=100, verbose_name='Рекомендований розмір')),
                ('recommended_infill', models.PositiveIntegerField(verbose_name='Рекомендоване заповнення, %')),
                ('recommended_detail', models.CharField(max_length=100, verbose_name='Рекомендована деталізація')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.category', verbose_name='Категорія')),
                ('recommended_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.material', verbose_name='Рекомендований матеріал')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model3d', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/', verbose_name='Зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне зображення')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.model3d', verbose_name='Модель')),
            ],
        ),
    ]
