# Generated by Django 5.2.14 on 2026-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='recommended_detail',
        ),
        migrations.AddField(
            model_name='model3d',
            name='recommended_layer_height',
            field=models.PositiveIntegerField(choices=[(100, '100 мкм'), (200, '200 мкм'), (300, '300 мкм')], default=200, verbose_name='Рекомендована висота шару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='recommended_wall_thickness',
            field=models.PositiveIntegerField(choices=[(1, '1 мм'), (2, '2 мм'), (3, '3 мм')], default=2, verbose_name='Рекомендована товщина стінок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model3d',
            name='recommended_infill',
            field=models.PositiveIntegerField(choices=[(5, '5%'), (10, '10%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], verbose_name='Рекомендоване заповнення'),
        ),
    ]
