# Generated by Django 5.2.14 on 2026-05-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_model3d_recommended_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('material', models.CharField(max_length=50, verbose_name='Матеріал')),
                ('size', models.PositiveIntegerField(verbose_name='Розмір')),
                ('layer_height', models.PositiveIntegerField(verbose_name='Висота шару')),
                ('wall_thickness', models.PositiveIntegerField(verbose_name='Товщина стінок')),
                ('infill', models.PositiveIntegerField(verbose_name='Заповнення')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('printing', 'Друкується'), ('completed', 'Завершено')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model3d', verbose_name='Модель')),
            ],
        ),
    ]
