# Generated by Django 5.2.14 on 2026-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('white', 'Білий'), ('black', 'Чорний'), ('gray', 'Сірий'), ('red', 'Червоний'), ('blue', 'Синій'), ('green', 'Зелений')], default='white', max_length=20, verbose_name='Колір'),
        ),
    ]
