# Generated by Django 5.2.14 on 2026-06-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_favorite_options_alter_favorite_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва якості')),
                ('layer_height', models.PositiveIntegerField(choices=[(100, '100 мкм'), (200, '200 мкм'), (300, '300 мкм')], verbose_name='Висота шару')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='price_per_gram',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='recommended_layer_height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='layer_height',
        ),
        migrations.AddField(
            model_name='model3d',
            name='base_weight',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='Базова вага, г'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='complexity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коефіцієнт складності'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Орієнтовна вага, г'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='recommended_size',
            field=models.PositiveIntegerField(default=10, verbose_name='Рекомендований розмір, см'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='recommended_wall_thickness',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=4, verbose_name='Рекомендована товщина стінок, мм'),
        ),
        migrations.AlterField(
            model_name='order',
            name='infill',
            field=models.PositiveIntegerField(verbose_name='Заповнення, %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.material', verbose_name='Матеріал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Розмір, см'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('printing', 'Друкується'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна ціна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wall_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Товщина стінок, мм'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='recommended_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.printquality', verbose_name='Рекомендована якість друку'),
        ),
        migrations.AddField(
            model_name='order',
            name='quality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.printquality', verbose_name='Якість друку'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за грам')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.material', verbose_name='Матеріал')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='main.printquality', verbose_name='Якість друку')),
            ],
            options={
                'verbose_name': 'Ціна матеріалу',
                'verbose_name_plural': 'Ціни матеріалів',
                'unique_together': {('material', 'quality')},
            },
        ),
    ]
