# Generated by Django 5.2.14 on 2026-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_printquality_remove_material_price_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='base_size',
            field=models.PositiveIntegerField(default=10, verbose_name='Базовий розмір моделі, см'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='supports_required',
            field=models.BooleanField(default=False, verbose_name='Потребує підтримок'),
        ),
    ]
