# Generated by Django 5.2.14 on 2026-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_model3d_base_size_model3d_supports_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='recommended_wall_thickness',
            field=models.PositiveIntegerField(choices=[(1, '1 мм'), (2, '2 мм'), (3, '3 мм')], default=2, verbose_name='Рекомендована товщина стінок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wall_thickness',
            field=models.PositiveIntegerField(choices=[(1, '1 мм'), (2, '2 мм'), (3, '3 мм')], default=2, verbose_name='Товщина стінок'),
        ),
    ]
