# Generated by Django 5.2.14 on 2026-06-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_model3d_recommended_wall_thickness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='infill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wall_thickness',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва кольору')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код кольору')),
                ('materials', models.ManyToManyField(related_name='colors', to='main.material', verbose_name='Доступний для матеріалів')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Розмір, см')),
                ('wall_thickness', models.PositiveIntegerField(choices=[(1, '1 мм'), (2, '2 мм'), (3, '3 мм')], default=2, verbose_name='Товщина стінок')),
                ('infill', models.PositiveIntegerField(verbose_name='Заповнення, %')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('estimated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart', verbose_name='Кошик')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.material', verbose_name='Матеріал')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model3d', verbose_name='Модель')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.printquality', verbose_name='Якість друку')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.color', verbose_name='Колір')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Розмір, см')),
                ('wall_thickness', models.PositiveIntegerField(choices=[(1, '1 мм'), (2, '2 мм'), (3, '3 мм')], default=2, verbose_name='Товщина стінок')),
                ('infill', models.PositiveIntegerField(verbose_name='Заповнення, %')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('estimated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Орієнтовна вага, г')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна позиції')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.color', verbose_name='Колір')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.material', verbose_name='Матеріал')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model3d', verbose_name='Модель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Замовлення')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.printquality', verbose_name='Якість друку')),
            ],
        ),
    ]
