# Generated by Django 5.2.14 on 2026-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_order_color_remove_order_estimated_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='infill',
            field=models.PositiveIntegerField(choices=[(5, '5%'), (10, '10%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=25, verbose_name='Заповнення, %'),
        ),
    ]
