# Generated by Django 5.2.14 on 2026-06-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cartitem_infill'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='max_size',
            field=models.PositiveIntegerField(default=25, verbose_name='Максимальний розмір, см'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='min_size',
            field=models.PositiveIntegerField(default=3, verbose_name='Мінімальний розмір, см'),
        ),
    ]
