# Generated by Django 5.2.14 on 2026-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_model3d_max_size_model3d_min_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Не вказано', max_length=100, verbose_name='Населений пункт'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Не вказано', max_length=255, verbose_name='Адреса / відділення пошти'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('ukr_poshta', 'Укрпошта')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.CharField(default='Оплата при отриманні замовлення на пошті', max_length=100, verbose_name='Оплата'),
        ),
    ]
